#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo apt update
sudo apt install -y nginx

sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
