#!/bin/bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!
sudo apt-get -y update
sudo apt-get -y  install nginx
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
